

POST http://127.0.0.1:8000/sensors/sensorData
Content-Type: application/json

{
    "TEMP": 25.5,
    "CO": 0.5,
    "H2": 42.0,
    "CH4": 31.0,
    "LPG": 2.0,
    "PROPANE": 42.2,
    "ALCOHOL": 44.0,
    "SMOKE": 0.1,
    "rid": 1
}


###
POST http://127.0.0.1:8000/sensors/systemAlarm
Content-Type: application/json

{"alertStatus": true,
  "rid": 1
}


###
GET http://127.0.0.1:8000/sensors/getSysStatus

###
POST http://172.20.10.2:8000/sensors/createSensorEntry
Content-Type: application/json


{"key": "TRFAMuEiNzxUUaskISKiICSRL3r8rfQV"}



###
GET http://172.20.10.2:8000/sensors/testAu
Authorization: Token Sg2SrOiNhRdXSAMHgN5J1QrAtShltSkm


###

POST http://127.0.0.1:8000/sensors/stopAlert
Content-Type: application/json


###
GET http://172.20.10.2:8000/sensors/getVideoById?id=4
Content-Type: application/json

###
GET http://127.0.0.1:8000/sensors/getAllVideos
Content-Type: application/json

###
GET http://127.0.0.1:8000/sensors/media?id=1
Content-Type: application/json


