

###
GET http://127.0.0.1:8000/api/testReact
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/getRooms
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/getAverageAll
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/getAverageRid?id=1
Content-Type: application/json

{
  "id": 3
}


###

GET http://127.0.0.1:8000/api/getRoomMetricDay
Content-Type: application/json

{
  "id": 1
}


###

POST http://127.0.0.1:8000/api/renameRoom
Content-Type: application/json

{
  "name": "London",
  "id": 3
}